### ISSUE TITLE
Download/Delete data options should only be enabled if the GDPR option is enabled

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/contact-form-ready#28]
![image](https://user-images.githubusercontent.com/41285248/55724829-8a6cbc00-5a0c-11e9-84aa-4d769dcf6d4f.png)

Should implement an if statement so if the GDPR Compliance module is not enabled that these checkboxes aren't checked.

**Comment by Abelc01** [comment]
Fixed Bug
