### ISSUE TITLE
Fix GDPR Warning Buttons and Links

### ISSUE THREAD

**Issue by MatthewCodeCabin** [CodeCabin/contact-form-ready#70]
Some links don't go anywhere and some are old.

Privacy Button when in the New Contact Form Menu has bad URI.

**Comment by Niaz-Ul-Haque** [comment]
Can I get assigned to this issue? I'll be sure to complete it and submit a PR for review by the end of today. Thank you!

**Comment by MatthewCodeCabin** [comment]
Hi @Niaz-Ul-Haque 

Thank you so much for your time.

We appreciate your offer, however we have already resolved the GDPR Warning Button and Link issues.

Thank you once again for your kind offer!
